name: Deploy static website to non prod environment
on: [push]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.0
      - name: Install Gatsby and build site
        run: |
          npm install -g gatsby-cli
          npm install
          gatsby build
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ github.sha }}
          path: public/
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.sha }}
      - name: Ls
        run: ls -la